import { precacheAndRoute } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { NetworkFirst, CacheFirst } from 'workbox-strategies'

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Cache Solana RPC calls
registerRoute(
  ({ url }) => url.hostname === 'api.mainnet-beta.solana.com',
  new NetworkFirst({
    cacheName: 'solana-rpc',
    plugins: [
      { cachedResponseWillBeUsed: async ({ cacheName, request, matchOptions, cachedResponse, event }) => {
        if (cachedResponse) {
          const dateHeader = cachedResponse.headers.get('date')
          if (dateHeader) {
            const age = (Date.now() - new Date(dateHeader).getTime()) / 1000
            if (age > 3600) return null
          }
        }
        return cachedResponse
      }}
    ]
  })
)

// Cache Stripe API calls
registerRoute(
  ({ url }) => url.hostname === 'api.stripe.com',
  new NetworkFirst({
    cacheName: 'stripe-api',
  })
)

// Cache images
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      { expired: () => {} }
    ]
  })
)

// Offline fallback - show the app shell
self.addEventListener('fetch', (event) => {
  // Navigation requests get network-first with app shell fallback
  if (event.request.mode === 'navigate') {
    event.respondWith(
      fetch(event.request).catch(() => caches.match('/index.html'))
    )
  }
})